line-length = 100
target-version = "py39"
exclude = [
  ".git",
  ".pylint",
  "__pycache__",
  "apptainer",
  "kalshi_ingestor.sif",
  "kalshi_pgdata",
  "log",
  "postgres_16.sif",
]

[lint]
select = ["E", "F", "W", "I"]
